/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-06-02 20:26:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Java/eclipse-jee-mars-2/workspace3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/rupeng-front/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308098170000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1478707862643L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 String ctxPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(ctxPath);
      out.write("/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(ctxPath);
      out.write("/css/index.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(ctxPath);
      out.write("/lib/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(ctxPath);
      out.write("/lib/unslider.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath);
      out.write("/js/index.js\"></script>\r\n");
      out.write("<title>如鹏网——专注于大学生的IT职业技能在线学习社区</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--登陆注册部分-->\r\n");
      out.write("\t<div class=\"nav-bar container-fluid\">\r\n");
      out.write("\t\t<div class=\"container center\">\r\n");
      out.write("\t\t\t<div style=\"float: right;\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/jsp/index.jsp(24,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<li class=\"f12\"><a href=\"");
            out.print(request.getContextPath());
            out.write("/user/userInfo.do\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(empty user.name)?user.email:user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("\t\t\t\t\t<li class=\"f12\"><a href=\"");
            out.print(request.getContextPath());
            out.write("/user/logout.do\">退出</a></li>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /WEB-INF/jsp/index.jsp(28,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<li class=\"f12\"><a href=\"");
            out.print(request.getContextPath());
            out.write("/user/login.do\">登录</a></li>\r\n");
            out.write("\t\t\t\t\t<li class=\"f12\"><a href=\"");
            out.print(request.getContextPath());
            out.write("/user/register.do\">注册</a></li>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--主体-->\r\n");
      out.write("\t<!--logo-->\r\n");
      out.write("\t<div class=\"container center logo-box\">\r\n");
      out.write("\t\t<div class=\"fl logo\">\r\n");
      out.write("\t\t\t<a href=\"/\" title=\"如鹏网\"> <img alt=\"如鹏网\"\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images/logo.png\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fl slogan\">\r\n");
      out.write("\t\t\t<h1 class=\"f16\">专注于大学生就业的在线教育</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a href=\"javascript:;\" id=\"btn-menu\" class=\"btn-menu mobile fr\">菜单</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--导航-->\r\n");
      out.write("\t<div class=\"container center nav-box\">\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul id=\"nav-list\" class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li class=\"all\"><a class=\"f18\" href=\"#\" title=\"全部课程\">全部课程</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"sub-list\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/topics/javaeecourses/index.shtml\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"Java训练营\"> <img alt=\"Java训练营\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images/85x85-java.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Java训练营</h2> <span>有趣、逗逼</span> <span>SSH、SSM架构通吃</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li title=\".Net训练营\"><a href=\"/xlynet.shtml\" title=\".Net训练营\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\".Net训练营\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images/85x85-net.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>.Net训练营</h2> <span>剖析.Net内部原理</span> <span>讲解大网站开发技术</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li title=\"C语言训练营\"><a href=\"/News/10/338.shtml\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"C语言训练营\"> <img alt=\"C语言训练营\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images/85x85-c.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>C语言训练营</h2> <span>课余时间不浪费</span> <span>学点有用的</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"f16\" href=\"/News/10/165.shtml\" title=\"0元学\">“0元学”</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"f16\" href=\"/News/13/list_1.shtml\" title=\"就业喜报\">就业喜报</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"f16\" href=\"/aboutus.shtml\" title=\"关于如鹏\">关于如鹏</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"f16\" href=\"/wholearning.shtml\" title=\"他们正在学\">他们正在学</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container center\">\r\n");
      out.write("\t\t<!--图片轮播-->\r\n");
      out.write("\t\t<div class=\"slider-box\" id=\"slider-box\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li\r\n");
      out.write("\t\t\t\t\tstyle=\"background: url(");
      out.print(ctxPath);
      out.write("/images/slider1.png) 50% 50% no-repeat;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/News/10/338.shtml\" target=\"_blank\"></a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li\r\n");
      out.write("\t\t\t\t\tstyle=\"background: url(");
      out.print(ctxPath);
      out.write("/images/slider2.png) 50% 50% no-repeat;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/News/9/357.shtml\" target=\"_blank\"></a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li\r\n");
      out.write("\t\t\t\t\tstyle=\"background: url(");
      out.print(ctxPath);
      out.write("/images/slider3.png) 50% 50% no-repeat;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/News/9/368.shtml\" target=\"_blank\"></a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--如鹏消息-->\r\n");
      out.write("\t\t<div class=\"mess-box\">\r\n");
      out.write("\t\t\t<div class=\"mess-title\">如鹏消息</div>\r\n");
      out.write("\t\t\t<div class=\"mess-list\">\r\n");
      out.write("\t\t\t\t<ul class=\"list-icon\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/News/9/368.shtml\" target=\"_blank\">信哥哥、信同事、信自己，所以我们来了</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/News/13/363.shtml\" target=\"_blank\">如鹏老师最高兴的时刻是……</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/News/9/357.shtml\" target=\"_blank\">揭露那些对如鹏的抹黑</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"http://www.rupeng.com/Courses/Chapter/496\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color: red\" target=\"_blank\">甲骨文放弃Java，我们怎么办</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/News/9/373.shtml\" target=\"_blank\">如鹏训练营0820开班典礼</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/News/9/267.shtml\" target=\"_blank\">如鹏网出席全国青少年智创大会</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/News/9/310.shtml\" target=\"_blank\">感动！病床上手写的编程考试题</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/News/14/304.shtml\" target=\"_blank\">三十岁，java这条路，我才开始</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/News/9/302.shtml\" target=\"_blank\">如鹏网到中科院研究生院做讲座</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/News/13/295.shtml\" target=\"_blank\">应届生平均薪资8016元</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"mess-more\">\r\n");
      out.write("\t\t\t\t<a href=\"/News/9/list_1.shtml\" class=\"more\">更多&gt;&gt;</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--加入方式-->\r\n");
      out.write("\t\t<div class=\"join-box clearboth\">\r\n");
      out.write("\t\t\t<div class=\"fl consult\">\r\n");
      out.write("\t\t\t\t<a class=\"fw600 f15\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\thref=\"http://crm2.qq.com/portalpage/wpa.php?uin=800110472&aty=0&a=0&curl=&ty=1\"\r\n");
      out.write("\t\t\t\t\ttitle=\"咨询课程\">咨询课程</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"fl ml-7\">\r\n");
      out.write("\t\t\t\t<a href=\"/yuema.shtml\"><img alt=\"如鹏微信、微博、QQ群\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images/232x125-1.jpg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"fl ml-7\">\r\n");
      out.write("\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\thref=\"http://list.qq.com/cgi-bin/qf_invite?id=46c1bf5f1319f463adb1148d723dcfd77caf5158ad81c7c6\"\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\"><img alt=\"\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images//232x125-2.jpg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"fl ml-7\">\r\n");
      out.write("\t\t\t\t<a href=\"/News/10/269.shtml\"><img alt=\"\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images//232x125-3.jpg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"fl ml-7\">\r\n");
      out.write("\t\t\t\t<a href=\"/News/14/247.shtml\"><img alt=\"\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images//232x125-4.jpg\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--课程中心-->\r\n");
      out.write("\t<div class=\"lesson-box container-fluid\">\r\n");
      out.write("\t\t<div class=\"container center\">\r\n");
      out.write("\t\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t\t<i></i>\r\n");
      out.write("\t\t\t\t<h2 class=\"f22\">课程中心</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/topics/javaeecourses/index.shtml\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/371x208-java.jpg\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>学起来最轻松、最有趣的JavaEE就业课程</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-strong\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/topics/javaeecourses/index.shtml\">查看详情</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-weak\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"http://crm2.qq.com/portalpage/wpa.php?uin=800110472&aty=0&a=0&curl=&ty=1\">开班时间</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/xlynet.shtml\"><img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images/371x208-net.jpg\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>国内唯一讲解大型互联网架构的.Net课程！</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/xlynet.shtml\">查看详情</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-weak\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"http://crm2.qq.com/portalpage/wpa.php?uin=800110472&aty=0&a=0&curl=&ty=1\">开班时间</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/xlyandroid.shtml\"><img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print(ctxPath);
      out.write("/images/371x208-android.jpg\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>移动互联网时代，学Android不需要理由</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/xlyandroid.shtml\">查看详情</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-weak\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"http://crm2.qq.com/portalpage/wpa.php?uin=800110472&aty=0&a=0&curl=&ty=1\">开班时间</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"free-box container center\">\r\n");
      out.write("\t\t<div class=\"title-box\">\r\n");
      out.write("\t\t\t<i></i>\r\n");
      out.write("\t\t\t<h2 class=\"f22\">\r\n");
      out.write("\t\t\t\t<a href=\"freecourses.shtml\">免费课程</a>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<a href=\"freecourses.shtml\"\r\n");
      out.write("\t\t\t\tstyle=\"float: right; color: #57a9e2; font-size: 12px;\">更多&gt;&gt;</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<ul class=\"lesson-list\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">入门课程</span> <a href=\"/Courses/Index/66\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-1.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>C语言也能干大事之游戏开发</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span><span courseid=\"66\">2417</span>人正在学习</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/Courses/Index/66\">立即查看</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">答疑解惑</span> <a href=\"/Courses/Chapter/471\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-2.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>.Net为什么就业这么火</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span><span chapterid=\"471\">12368</span>人正在学</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/Courses/Chapter/471\">立即查看</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">最新视频</span> <a href=\"/Courses/Index/51\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-3.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>史上最有趣、最易懂的Java入门教程</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span><span courseid=\"51\">4897</span>人正在学</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/Courses/Index/51\">立即学习</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">真知灼见</span> <a href=\"/Courses/Chapter/496\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-4.png\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>听说Oracle要放弃Java了？我们怎么办？</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span><span chapterid=\"496\">4649</span>人正在学</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/Courses/Chapter/496\">立即学习</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">学点东西</span> <a href=\"/Courses/Chapter/497\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-5.png\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>校园一卡通的原理是什么？有什么漏洞可以利用？可以用C语言开发？</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span><span chapterid=\"497\">1258</span>人正在学</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/Courses/Chapter/497\">立即学习</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">最热视频</span> <a href=\"/Courses/Index/12\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-6.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>C语言也能干大事第三版</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span><span courseid=\"12\">12701</span>人正在学</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/Courses/Index/12\">立即学习</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">高大上</span> <a href=\"/Courses/Chapter/299\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-9.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>你想知道大型互联网站用的什么技术吗？</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span><span chapterid=\"299\">12550</span>人正在学</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/Courses/Chapter/299\">立即学习</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">深入教程</span> <a href=\"/Courses/Index/34\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-7.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>C语言也能干大事进阶篇：C语言开发网站</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span><span courseid=\"34\">6247</span>人正在学</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/Courses/Index/34\">立即学习</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">答疑解惑</span> <a href=\"/Courses/Chapter/379\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-8.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>大二开始找工作</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span><span chapterid=\"379\">2967</span>人正在学</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/Courses/Chapter/379\">立即学习</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tip\">答疑解惑</span> <a href=\"/News/9/13.shtml\"><img\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" src=\"");
      out.print(ctxPath);
      out.write("/images/220x123-10.jpg\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t<h3>你学习中遇到的疑惑都可以在这里解决</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"num join-num\">\r\n");
      out.write("\t\t\t\t\t\t\t<i></i> <span>百万人受益</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-strong\" href=\"/News/9/13.shtml\">立即查看</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid article-box\">\r\n");
      out.write("\t\t<div class=\"container center\">\r\n");
      out.write("\t\t\t<div class=\"news-1 news-box fl\">\r\n");
      out.write("\t\t\t\t<div class=\"tit-box\">\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/News/9/13.shtml\">解惑文章</a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t<a class=\"more\" href=\"/News/9/13.shtml\">更多&gt;&gt; </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-icon\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/8/260.shtml\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tit\">[答疑解惑]选择做程序员是对还是错</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"view\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i></i> <span>热门阅读</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/8/15.shtml\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tit\">【解惑】这么多技术我该怎么学</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"view\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i></i> <span>热门阅读</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/8/16.shtml\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tit\">【解惑】计算机学习速成法</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"view\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i></i> <span>热门阅读</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/8/39.shtml\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tit\">【解惑】我该怎么选择？选择就是放弃</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"view\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i></i> <span>热门阅读</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/8/43.shtml\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tit\">量变到质变的感觉及时间安排的原则</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"view\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i></i> <span>热门阅读</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/8/46.shtml\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tit\">一切编程语言都是纸老虎</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"view\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i></i> <span>热门阅读</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"news-2 news-box fr\">\r\n");
      out.write("\t\t\t\t<div class=\"tit-box\">\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/News/7/list_1.shtml\">招聘信息</a><small>JOB</small>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t<a class=\"more\" href=\"/News/7/list_1.shtml\">更多&gt;&gt; </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/9/308.shtml\">如鹏网招聘.Net老师、Java老师、班主任</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/7/271.shtml\">厦门停开心来如鹏招聘Java、.Net、Android程序员</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/7/278.shtml\">佛山八戒印刷网络公司来如鹏招聘.Net工程师</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/7/237.shtml\">广州、郑州、青岛三家公司到如鹏网招聘.net工程师</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/7/230.shtml\">郑州云计划来如鹏招聘Java、.Net、Android工程师</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/News/7/229.shtml\">上海匡正来如鹏网招聘Android工程师</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 页脚 -->\r\n");
      out.write("\t<div id=\"footerDiv\" class=\"footer\">\r\n");
      out.write("\t\t<div class=\"top container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"container center\">\r\n");
      out.write("\t\t\t\t<div class=\"left-box\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" title=\"加入我们\">加入我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" title=\"联系我们\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" title=\"付款方式\">付款方式</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" title=\"服务条款\">服务条款</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" title=\"版权声明\">版权声明</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" title=\"友情链接\">友情链接</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>热线电话：010-67877100</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>24小时热线：15910679760</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bottom container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"container center\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t®北京如鹏信息科技有限公司2008-2016 <a href=\"http://www.miitbeian.gov.cn/\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"_blank\">京ICP备14048059号-2</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
